### PR TITLE
fix: Increase contrast between selected messages and window background. Fixes #1110 (Plan B)

### LINKED ISSUE #1110: Visual clarity: contrast of message selection is extremely low
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Selected messages have a low contrast compared to unselected messages, making them hard to distinguish.

**To reproduce**

Fresh install Session Android, default theme, and select some messages.

In the below example, "Hi this is Alice" is selected, "Hi this is Carol" and "Hi this is Bob" are unselected, they look very closely.

The selected messages have a very closed color / darkness compared to unselected messages.
This makes a moderator's life harder because they often need to delete messages in bulk.

**Screenshots or logs**

Screen Shot 2023-02-09 at 5 27 51 am

**Smartphone (please complete the following information):**

 - Device: [Android Emulator Pixel 6]
 - OS: [e.g. Android 13.0]
 - Version of Session or latest commit hash: [Session 1.16.5]

**Additional context**

There are users reporting the message selection visual clarity issue was fixed in some earlier version, but then came back again after theming support was implemented. In other words, it might be a visual regression.

However, on 1.16.3 release note there was

> "Make selected message colours more visible, fix classic dark read indicator by @0x330a in #1031"

So this could be a disagreement on the sense of visibility as well. At least to me the selected message is not very different to unselected messages.

In any case, visual regression testing is tricky itself. According to [1], "This can result in tens or even hundreds of thousands of potential screens to test".
We might want to investigate specialized testing frameworks for visual regression like [2].

[1] https://applitools.com/blog/visual-ai/
[2] https://percy.io/

### PR DESCRIPTION
**Pull request by fracting**
### Contributor checklist

- [x] I have tested my contribution on these devices:
 * Virtual device Pixel 6 API 33, Android 13.0
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description

See https://github.com/oxen-io/session-android/issues/1110#issuecomment-1426331553 for screenshots.

### CODE REVIEW

**Comment by fracting** [comment]
I submitted two pull requests, will close one of them based on feedback, feel free to comment / vote.

Plan A: #1115

**Review by hjubb — APPROVED** [review]
Looks good! Is it possible to change the base to `dev`?

**Comment by fracting** [comment]
I rebased on dev and force pushed @hjubb

**Review by hjubb — APPROVED** [review]

**Comment by hjubb** [comment]
Thanks for that, merging now

**Pull request merged**
