### PR TITLE
[SES-538] Fix truncateIdForDisplay and add test

### PR DESCRIPTION
**Pull request by bemusementpark**
Screen Shot 2023-06-06 at 11 44 04 am

### CODE REVIEW

**Comment by burtonemily** [comment]
Still getting this issue, but it seems like it exists on other platforms also, so I unlinked this issue with the point release and we can probably raise this later.

**Comment by bemusementpark** [comment]
It's hard to be certain that the profile hasn't been set to the session id, maybe I should just check if the username is 58ish chars long with no white space, and truncate then.

**Comment by KeeJef** [comment]
What was the go here, does this fix an issue that if the users nickname was set to their Session ID then it will truncate their nickname so whole Session ID isnt visible?

**Comment by KeeJef** [comment]
Closing for now, discussed this and we want to take a more generalised approach to rendering of display names which centralises the logic into a similar manner to iOS, https://github.com/oxen-io/session-ios/blob/master/SessionMessagingKit/Database/Models/Profile.swift#L348 , will break this out into a separate ticket on Jira

**Pull request closed without merging**
