### PR TITLE
Split image from replies

### LINKED ISSUE #747: Media received not displaying in chat
**Code of conduct**

- [ x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

The image or gif sent by another user does not appear inline in the main chat.  The received message does not show any content.  A thumbnail can be seen of the image or gif when the message is quoted.

**To reproduce**

Have another user send an image or a gif in a closed or open group.  I've had the issue occur in both group types.  The issue does not occur consistently, but the image/gif doesn't appear more often than it appears.

**Screenshots**

Screenshot No. 1
de4ec774-d9b3-4ec3-94d5-375d7a448fb6

Screenshot No. 2
e0f69bb5-06e7-4249-b36b-154211368451

**Smartphone:**

 - Device: Google Pixel 4a
 - OS: Android 11 (CalyxOS v2.9.0)
 - Version of Session or latest commit hash: v1.11.9 (2215)

**Additional context**

Will provide upon request.

### PR DESCRIPTION
**Pull request by hjubb**
Fixes #747

### CODE REVIEW

**Comment by hardBSDk** [comment]
Why are you taking so long to merge this?

**Comment by hjubb** [comment]
hey @hardBSDk sorry this branch had a couple of issues that were preventing merge, I'll sync it with the latest and make sure those issues are resolved now :+1:

**Comment by hjubb** [comment]
@ceokot there's still the issue of the voice view not rendering properly here, maybe you might be able to find something :smile:

**Comment by hjubb** [comment]
This one should now work properly with the `DeletedMessageView` preventing the previously bound message from appearing over the top

**Review by ceokot — APPROVED** [review]

**Pull request merged**
