### PR TITLE
Add remove avatar dialog

### PR DESCRIPTION
**Pull request by bemusementpark**
Screen Shot 2023-05-17 at 1 51 27 pm
Screen Shot 2023-05-17 at 1 51 05 pm

### CODE REVIEW

**Comment by KeeJef** [comment]
Just a note, before we merge this we should determine what we are going to do with platform conventions in this case and perhaps more generally. There are some clear pros and cons between having platform agnostic UI vs following platform UI conventions. Our strategy thus far has been case by case but leaning towards platform agnostic UI's.

**Comment by bemusementpark** [comment]
Fair point, at the moment we have several Android framework buttons in dialogs, and it's low effort to implement, so we could just go ahead and modify this later when we do a dialog overhaul.

(Also I have another PR that fixes the button colors https://github.com/oxen-io/session-android/pull/1198)

**Comment by KeeJef** [comment]
Yeah i don't mind merging and changing later, as long as we do revisit this before this release goes live

**Comment by KeeJef** [comment]
Related to #1195 we will wait till the onboarding overhaul to add the ability to remove an avatar. At this point we will modify all Android modals to use the Session platform agnostic modal design. This PR can be modified and merged at that point

**Review by hjubb — APPROVED** [review]

**Pull request merged**
