### PR TITLE
Nicknames

### PR DESCRIPTION
**Pull request by RyanRory**
Introduce a new model `Contact` to implement the client-side nickname and plan to replace the `Recipient` and `Address` with this new `Contact` model.

### CODE REVIEW

**Comment by nielsandriesse** [comment]
It'd be nice if we could introduce a `Contact` model like we did on iOS as part of this PR, so that we can start moving away from the whole `Recipient`/`Address` setup.

**Comment by Brice-W** [comment]
Hey @RyanRory I just gave that PR a quick test, here's what I've found:
- There is no button to save the input
- The ‘x’ on the right doesn’t cancel the changes
- If I have a nickname set, then I edit the nickname and set nothing, then the name reverts to the ID of the contact. I think in that case it can be reverted to the real name of the user.

**Comment by RyanRory** [comment]
@Brice-W Thanks for the testing.
We'll figure out where to put a button to save the input during the rebuild of the conversation screen. I just use the action button on the soft keyboard for now to save the nickname. The other two bugs are fixed.

**Comment by nielsandriesse** [comment]
Regarding the `Contact` model, what I meant is that we introduce it and also start updating it whenever a user's profile data is updated. That way we'll soon be able to delete the old way of doing things without requiring a migration.

**Comment by Brice-W** [comment]
@RyanRory I've tested that PR again, just one little thing: if you remove a contact's nickname, it sets the original name back, but it's still using the deleted nickname in the groups + group creation / edition UI.

**Pull request merged**
