### PR TITLE
[WIP] SQLCipher 4 Upgrade

### PR DESCRIPTION
**Pull request by mpretty-cyro**
**TODOs**
- [x] Update to SQLCipher 4
- [x] Add migration for existing database
- [x] Performance testing of migration (need a large test DB for this - will eventually be a destructive operation)
- [ ] Delete the old database file
- [ ] Communicate errors back to the user somehow

### CODE REVIEW

**Comment by Flam3z** [comment]
May I ask how will this improve session?

**Comment by mpretty-cyro** [comment]
> May I ask how will this improve session?

Sure, there are a couple of reasons:
- The main reason is that the previous version we were using (3.5.9-S3) was released at the end of 2017, there have been a large number of fixes and improvements in the last 5 years
  - [SQLCipher changes](https://github.com/sqlcipher/sqlcipher/blob/master/CHANGELOG.md#342---december-2017---342-changes)
  - [SQLite changes](https://www.sqlite.org/changes.html) (I believe the the old SQLCipher version used `2017-08-24 (3.20.1)`)
- Another benefit is that version `4.5.2` also includes support for connection pooling which allows for concurrent reads (with the current version it appears that both reads could block writes) so this _may_ have some performance improvements ([you can read more here](https://www.zetetic.net/blog/2022/05/11/sqlcipher-android-refresh/))
  - **Note:** From the limited testing I was able to do I didn't notice significant performance improvements from this so don't expect anything amazing

**Comment by Flam3z** [comment]
> > May I ask how will this improve session?
> 
> Sure, there are a couple of reasons:
> 
> * The main reason is that the previous version we were using (3.5.9-S3) was released at the end of 2017, there have been a large number of fixes and improvements in the last 5 years
>   
>   * [SQLCipher changes](https://github.com/sqlcipher/sqlcipher/blob/master/CHANGELOG.md#342---december-2017---342-changes)
>   * [SQLite changes](https://www.sqlite.org/changes.html) (I believe the the old SQLCipher version used `2017-08-24 (3.20.1)`)
> * Another benefit is that version `4.5.2` also includes support for connection pooling which allows for concurrent reads (with the current version it appears that both reads could block writes) so this _may_ have some performance improvements ([you can read more here](https://www.zetetic.net/blog/2022/05/11/sqlcipher-android-refresh/))
>   
>   * **Note:** From the limited testing I was able to do I didn't notice significant performance improvements from this so don't expect anything amazing

Thanks for the response.

**Comment by mpretty-cyro** [comment]
Combining this into #1069 (not going to merge them separately)

**Pull request closed without merging**
