### PR TITLE
Make the session more beautiful.

### PR DESCRIPTION
**Pull request by ref6tn53yp**
- [x] I have tested my contribution on these devices:
 * Device Mi 10S, Android 13.0.6
 * Device Mi 6, Android Z.Y
 * Virtual device Pixel 5 , Android 12.0.0
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description

Hello, thank you very much for your project. It's very good in all aspects, but we don't think the interface is very beautiful. So we hope to make the project better. At present, the wechat interface in China is very good. In addition, signal is also very good. So we have changed some interfaces and hope to merge them into your warehouse. Of course, there are many changes this time. If you originally merged such molecules, What can be changed and how much can be changed can be further discussed. The main changes are as follows:

- Most interface buttons are about the same width as the screen.

- The outer margin of most interfaces is 16dp

- All avatars are rounded rectangles, not rounded corners, because rectangles can display more information.

- In the session list interface, the font of unimportant text (message not read, last message, time) becomes smaller and the color becomes lighter.

- In the chat interface (session details interface), the user's Avatar becomes larger, the font of unimportant text (time, user nickname, quoted message) becomes smaller, and the color becomes lighter.

- Increase the height of all buttons.

- The height of the search input box in the main interface increases.

Here are some screenshots：

### CODE REVIEW

**Comment by hjubb** [comment]
hey @ref6tn53yp thanks for the PR! We're actually looking at overhauling and allowing more customisation regarding themes in the app currently, I think it will be good to incorporate some of these cleaner layout files. For things like square avatars, I think I can try to make those available as styleable attributes to be easily changed, so that it can be enabled if people want that option from their own settings, I'll try to integrate this PR and let you know if there is any difficulties. Thanks again!

**Comment by ref6tn53yp** [comment]
@hjubb Well, OK. In addition, for style, you can refer to signal or wechat in China. Personally, I think the UI of these software is very beautiful.

**Comment by ref6tn53yp** [comment]
@hjubb Well, OK. In addition, for style, you can refer to signal or wechat in China. Personally, I think the UI of these software is very beautiful.

**Comment by hardBSDk** [comment]
@ref6tn53yp

https://github.com/oxen-io/session-android/pull/913#issuecomment-1179742661

**Comment by KeeJef** [comment]
Hey @ref6tn53yp I've spoken with the team about the visual changes contained in this PR, and they don't quite fit with our visual style right now. We are releasing a new update soon which will update the theming of app (mostly menu and color redesigns), hopefully some of these changes will be satisfactory to you, until then i will be closing this PR. Thanks!

**Pull request closed without merging**
